apiVersion: v1
kind: Pod
metadata:
  name: starter
  labels:
    app: podder
spec:
  containers:
    - name: starter
      image: skwiwel/pod-contagion:starter
      args:
        - "-http=0.0.0.0:80"
        - "-health=0.0.0.0:81"
      ports:
        - name: http
          containerPort: 80
        - name: health
          containerPort: 81
      resources:
          limits:
            cpu: 0.01
            memory: "10Mi"