apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic
spec:
  replicas: 10
  selector:
    matchLabels:
      app: podder
  template:
    metadata:
      labels:
        app: podder
    spec:
      containers:
        - name: podder
          image: "skwiwel/pod-contagion:generic"
          args:
            - "-http=0.0.0.0:80"
            - "-health=0.0.0.0:81"
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
          resources:
            limits:
              cpu: 0.01
              memory: "10Mi"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 81
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 81
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1