apiVersion: apps/v1
kind: Deployment
metadata:
  name: podder
 spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: podder
    spec:
      containers:
        - name: podder
          image: "skwiwel/podder:latest"
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
          resources:
            limits:
              cpu: 0.1
              memory: "10Mi"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 81
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 81
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1